CREATE TABLE countries (
	iso CHAR(2) NOT NULL PRIMARY KEY,
	iso3 char(3) NOT NULL,
	numcode SMALLINT,
	nome VARCHAR(255) NOT NULL
);

INSERT INTO countries VALUES ('AF', 'AFG', '004', 'Afeganistão');
INSERT INTO countries VALUES ('ZA', 'ZAF', '710', 'África do Sul');
INSERT INTO countries VALUES ('AX', 'ALA', '248', 'Åland, Ilhas');
INSERT INTO countries VALUES ('AL', 'ALB', '008', 'Albânia');
INSERT INTO countries VALUES ('DE', 'DEU', '276', 'Alemanha');
INSERT INTO countries VALUES ('AD', 'AND', '020', 'Andorra');
INSERT INTO countries VALUES ('AO', 'AGO', '024', 'Angola');
INSERT INTO countries VALUES ('AI', 'AIA', '660', 'Anguilla');
INSERT INTO countries VALUES ('AQ', 'ATA', '010', 'Antárctida');
INSERT INTO countries VALUES ('AG', 'ATG', '028', 'Antigua e Barbuda');
INSERT INTO countries VALUES ('AN', 'ANT', '530', 'Antilhas Holandesas');
INSERT INTO countries VALUES ('SA', 'SAU', '682', 'Arábia Saudita');
INSERT INTO countries VALUES ('DZ', 'DZA', '012', 'Argélia');
INSERT INTO countries VALUES ('AR', 'ARG', '032', 'Argentina');
INSERT INTO countries VALUES ('AM', 'ARM', '051', 'Arménia');
INSERT INTO countries VALUES ('AW', 'ABW', '533', 'Aruba');
INSERT INTO countries VALUES ('AU', 'AUS', '036', 'Austrália');
INSERT INTO countries VALUES ('AT', 'AUT', '040', 'Áustria');
INSERT INTO countries VALUES ('AZ', 'AZE', '031', 'Azerbeijão');
INSERT INTO countries VALUES ('BS', 'BHS', '044', 'Bahamas');
INSERT INTO countries VALUES ('BH', 'BHR', '048', 'Bahrain');
INSERT INTO countries VALUES ('BD', 'BGD', '050', 'Bangladesh');
INSERT INTO countries VALUES ('BB', 'BRB', '052', 'Barbados');
INSERT INTO countries VALUES ('BE', 'BEL', '056', 'Bélgica');
INSERT INTO countries VALUES ('BZ', 'BLZ', '084', 'Belize');
INSERT INTO countries VALUES ('BJ', 'BEN', '204', 'Benin');
INSERT INTO countries VALUES ('BM', 'BMU', '060', 'Bermuda');
INSERT INTO countries VALUES ('BY', 'BLR', '112', 'Bielo-Rússia');
INSERT INTO countries VALUES ('BO', 'BOL', '068', 'Bolívia');
INSERT INTO countries VALUES ('BA', 'BIH', '070', 'Bósnia-Herzegovina');
INSERT INTO countries VALUES ('BW', 'BWA', '072', 'Botswana');
INSERT INTO countries VALUES ('BV', 'BVT', '074', 'Bouvet, Ilha');
INSERT INTO countries VALUES ('BR', 'BRA', '076', 'Brasil');
INSERT INTO countries VALUES ('BN', 'BRN', '096', 'Brunei');
INSERT INTO countries VALUES ('BG', 'BGR', '100', 'Bulgária');
INSERT INTO countries VALUES ('BF', 'BFA', '854', 'Burkina Faso');
INSERT INTO countries VALUES ('BI', 'BDI', '108', 'Burundi');
INSERT INTO countries VALUES ('BT', 'BTN', '064', 'Butão');
INSERT INTO countries VALUES ('CV', 'CPV', '132', 'Cabo Verde');
INSERT INTO countries VALUES ('KH', 'KHM', '116', 'Cambodja');
INSERT INTO countries VALUES ('CM', 'CMR', '120', 'Camarões');
INSERT INTO countries VALUES ('CA', 'CAN', '124', 'Canadá');
INSERT INTO countries VALUES ('KY', 'CYM', '136', 'Cayman, Ilhas');
INSERT INTO countries VALUES ('KZ', 'KAZ', '398', 'Cazaquistão');
INSERT INTO countries VALUES ('CF', 'CAF', '140', 'Centro-africana, República');
INSERT INTO countries VALUES ('TD', 'TCD', '148', 'Chade');
INSERT INTO countries VALUES ('CZ', 'CZE', '203', 'Checa, República');
INSERT INTO countries VALUES ('CL', 'CHL', '152', 'Chile');
INSERT INTO countries VALUES ('CN', 'CHN', '156', 'China');
INSERT INTO countries VALUES ('CY', 'CYP', '196', 'Chipre');
INSERT INTO countries VALUES ('CX', 'CXR', '162', 'Christmas, Ilha');
INSERT INTO countries VALUES ('CC', 'CCK', '166', 'Cocos, Ilhas');
INSERT INTO countries VALUES ('CO', 'COL', '170', 'Colômbia');
INSERT INTO countries VALUES ('KM', 'COM', '174', 'Comores');
INSERT INTO countries VALUES ('CG', 'COG', '178', 'Congo, República do');
INSERT INTO countries VALUES ('CD', 'COD', '180', 'Congo, República Democrática do (antigo Zaire)');
INSERT INTO countries VALUES ('CK', 'COK', '184', 'Cook, Ilhas');
INSERT INTO countries VALUES ('KR', 'KOR', '410', 'Coreia do Sul');
INSERT INTO countries VALUES ('KP', 'PRK', '408', 'Coreia, República Democrática da (Coreia do Norte)');
INSERT INTO countries VALUES ('CI', 'CIV', '384', 'Costa do Marfim');
INSERT INTO countries VALUES ('CR', 'CRI', '188', 'Costa Rica');
INSERT INTO countries VALUES ('HR', 'HRV', '191', 'Croácia');
INSERT INTO countries VALUES ('CU', 'CUB', '192', 'Cuba');
INSERT INTO countries VALUES ('DK', 'DNK', '208', 'Dinamarca');
INSERT INTO countries VALUES ('DJ', 'DJI', '262', 'Djibouti');
INSERT INTO countries VALUES ('DM', 'DMA', '212', 'Dominica');
INSERT INTO countries VALUES ('DO', 'DOM', '214', 'Dominicana, República');
INSERT INTO countries VALUES ('EG', 'EGY', '818', 'Egipto');
INSERT INTO countries VALUES ('SV', 'SLV', '222', 'El Salvador');
INSERT INTO countries VALUES ('AE', 'ARE', '784', 'Emiratos Árabes Unidos');
INSERT INTO countries VALUES ('EC', 'ECU', '218', 'Equador');
INSERT INTO countries VALUES ('ER', 'ERI', '232', 'Eritreia');
INSERT INTO countries VALUES ('SK', 'SVK', '703', 'Eslováquia');
INSERT INTO countries VALUES ('SI', 'SVN', '705', 'Eslovénia');
INSERT INTO countries VALUES ('ES', 'ESP', '724', 'Espanha');
INSERT INTO countries VALUES ('US', 'USA', '840', 'Estados Unidos da América');
INSERT INTO countries VALUES ('EE', 'EST', '233', 'Estónia');
INSERT INTO countries VALUES ('ET', 'ETH', '231', 'Etiópia');
INSERT INTO countries VALUES ('FO', 'FRO', '234', 'Faroe, Ilhas');
INSERT INTO countries VALUES ('FJ', 'FJI', '242', 'Fiji');
INSERT INTO countries VALUES ('PH', 'PHL', '608', 'Filipinas');
INSERT INTO countries VALUES ('FI', 'FIN', '246', 'Finlândia');
INSERT INTO countries VALUES ('FR', 'FRA', '250', 'França');
INSERT INTO countries VALUES ('GA', 'GAB', '266', 'Gabão');
INSERT INTO countries VALUES ('GM', 'GMB', '270', 'Gâmbia');
INSERT INTO countries VALUES ('GH', 'GHA', '288', 'Gana');
INSERT INTO countries VALUES ('GE', 'GEO', '268', 'Geórgia');
INSERT INTO countries VALUES ('GS', 'SGS', '239', 'Geórgia do Sul e Sandwich do Sul, Ilhas');
INSERT INTO countries VALUES ('GI', 'GIB', '292', 'Gibraltar');
INSERT INTO countries VALUES ('GR', 'GRC', '300', 'Grécia');
INSERT INTO countries VALUES ('GD', 'GRD', '308', 'Grenada');
INSERT INTO countries VALUES ('GL', 'GRL', '304', 'Gronelândia');
INSERT INTO countries VALUES ('GP', 'GLP', '312', 'Guadeloupe');
INSERT INTO countries VALUES ('GU', 'GUM', '316', 'Guam');
INSERT INTO countries VALUES ('GT', 'GTM', '320', 'Guatemala');
INSERT INTO countries VALUES ('GG', 'GGY', '831', 'Guernsey');
INSERT INTO countries VALUES ('GY', 'GUY', '328', 'Guiana');
INSERT INTO countries VALUES ('GF', 'GUF', '254', 'Guiana Francesa');
INSERT INTO countries VALUES ('GW', 'GNB', '624', 'Guiné-Bissau');
INSERT INTO countries VALUES ('GN', 'GIN', '324', 'Guiné-Conacri');
INSERT INTO countries VALUES ('GQ', 'GNQ', '226', 'Guiné Equatorial');
INSERT INTO countries VALUES ('HT', 'HTI', '332', 'Haiti');
INSERT INTO countries VALUES ('HM', 'HMD', '334', 'Heard e Ilhas McDonald, Ilha');
INSERT INTO countries VALUES ('HN', 'HND', '340', 'Honduras');
INSERT INTO countries VALUES ('HK', 'HKG', '344', 'Hong Kong');
INSERT INTO countries VALUES ('HU', 'HUN', '348', 'Hungria');
INSERT INTO countries VALUES ('YE', 'YEM', '887', 'Iémen');
INSERT INTO countries VALUES ('IN', 'IND', '356', 'Índia');
INSERT INTO countries VALUES ('ID', 'IDN', '360', 'Indonésia');
INSERT INTO countries VALUES ('IQ', 'IRQ', '368', 'Iraque');
INSERT INTO countries VALUES ('IR', 'IRN', '364', 'Irão');
INSERT INTO countries VALUES ('IE', 'IRL', '372', 'Irlanda');
INSERT INTO countries VALUES ('IS', 'ISL', '352', 'Islândia');
INSERT INTO countries VALUES ('IL', 'ISR', '376', 'Israel');
INSERT INTO countries VALUES ('IT', 'ITA', '380', 'Itália');
INSERT INTO countries VALUES ('JM', 'JAM', '388', 'Jamaica');
INSERT INTO countries VALUES ('JP', 'JPN', '392', 'Japão');
INSERT INTO countries VALUES ('JE', 'JEY', '832', 'Jersey');
INSERT INTO countries VALUES ('JO', 'JOR', '400', 'Jordânia');
INSERT INTO countries VALUES ('KI', 'KIR', '296', 'Kiribati');
INSERT INTO countries VALUES ('KW', 'KWT', '414', 'Kuwait');
INSERT INTO countries VALUES ('LA', 'LAO', '418', 'Laos');
INSERT INTO countries VALUES ('LS', 'LSO', '426', 'Lesoto');
INSERT INTO countries VALUES ('LV', 'LVA', '428', 'Letónia');
INSERT INTO countries VALUES ('LB', 'LBN', '422', 'Líbano');
INSERT INTO countries VALUES ('LR', 'LBR', '430', 'Libéria');
INSERT INTO countries VALUES ('LY', 'LBY', '434', 'Líbia');
INSERT INTO countries VALUES ('LI', 'LIE', '438', 'Liechtenstein');
INSERT INTO countries VALUES ('LT', 'LTU', '440', 'Lituânia');
INSERT INTO countries VALUES ('LU', 'LUX', '442', 'Luxemburgo');
INSERT INTO countries VALUES ('MO', 'MAC', '446', 'Macau');
INSERT INTO countries VALUES ('MK', 'MKD', '807', 'Macedónia, República da');
INSERT INTO countries VALUES ('MG', 'MDG', '450', 'Madagáscar');
INSERT INTO countries VALUES ('MY', 'MYS', '458', 'Malásia');
INSERT INTO countries VALUES ('MW', 'MWI', '454', 'Malawi');
INSERT INTO countries VALUES ('MV', 'MDV', '462', 'Maldivas');
INSERT INTO countries VALUES ('ML', 'MLI', '466', 'Mali');
INSERT INTO countries VALUES ('MT', 'MLT', '470', 'Malta');
INSERT INTO countries VALUES ('FK', 'FLK', '238', 'Malvinas, Ilhas (Falkland)');
INSERT INTO countries VALUES ('IM', 'IMN', '833', 'Man, Ilha de');
INSERT INTO countries VALUES ('MP', 'MNP', '580', 'Marianas Setentrionais');
INSERT INTO countries VALUES ('MA', 'MAR', '504', 'Marrocos');
INSERT INTO countries VALUES ('MH', 'MHL', '584', 'Marshall, Ilhas');
INSERT INTO countries VALUES ('MQ', 'MTQ', '474', 'Martinica');
INSERT INTO countries VALUES ('MU', 'MUS', '480', 'Maurícia');
INSERT INTO countries VALUES ('MR', 'MRT', '478', 'Mauritânia');
INSERT INTO countries VALUES ('YT', 'MYT', '175', 'Mayotte');
INSERT INTO countries VALUES ('UM', 'UMI', '581', 'Menores Distantes dos Estados Unidos, Ilhas');
INSERT INTO countries VALUES ('MX', 'MEX', '484', 'México');
INSERT INTO countries VALUES ('MM', 'MMR', '104', 'Myanmar (antiga Birmânia)');
INSERT INTO countries VALUES ('FM', 'FSM', '583', 'Micronésia, Estados Federados da');
INSERT INTO countries VALUES ('MZ', 'MOZ', '508', 'Moçambique');
INSERT INTO countries VALUES ('MD', 'MDA', '498', 'Moldávia');
INSERT INTO countries VALUES ('MC', 'MCO', '492', 'Mónaco');
INSERT INTO countries VALUES ('MN', 'MNG', '496', 'Mongólia');
INSERT INTO countries VALUES ('ME', 'MNE', '499', 'Montenegro');
INSERT INTO countries VALUES ('MS', 'MSR', '500', 'Montserrat');
INSERT INTO countries VALUES ('NA', 'NAM', '516', 'Namíbia');
INSERT INTO countries VALUES ('NR', 'NRU', '520', 'Nauru');
INSERT INTO countries VALUES ('NP', 'NPL', '524', 'Nepal');
INSERT INTO countries VALUES ('NI', 'NIC', '558', 'Nicarágua');
INSERT INTO countries VALUES ('NE', 'NER', '562', 'Níger');
INSERT INTO countries VALUES ('NG', 'NGA', '566', 'Nigéria');
INSERT INTO countries VALUES ('NU', 'NIU', '570', 'Niue');
INSERT INTO countries VALUES ('NF', 'NFK', '574', 'Norfolk, Ilha');
INSERT INTO countries VALUES ('NO', 'NOR', '578', 'Noruega');
INSERT INTO countries VALUES ('NC', 'NCL', '540', 'Nova Caledónia');
INSERT INTO countries VALUES ('NZ', 'NZL', '554', 'Nova Zelândia (Aotearoa)');
INSERT INTO countries VALUES ('OM', 'OMN', '512', 'Oman');
INSERT INTO countries VALUES ('NL', 'NLD', '528', 'Países Baixos (Holanda)');
INSERT INTO countries VALUES ('PW', 'PLW', '585', 'Palau');
INSERT INTO countries VALUES ('PS', 'PSE', '275', 'Palestina');
INSERT INTO countries VALUES ('PA', 'PAN', '591', 'Panamá');
INSERT INTO countries VALUES ('PG', 'PNG', '598', 'Papua-Nova Guiné');
INSERT INTO countries VALUES ('PK', 'PAK', '586', 'Paquistão');
INSERT INTO countries VALUES ('PY', 'PRY', '600', 'Paraguai');
INSERT INTO countries VALUES ('PE', 'PER', '604', 'Peru');
INSERT INTO countries VALUES ('PN', 'PCN', '612', 'Pitcairn');
INSERT INTO countries VALUES ('PF', 'PYF', '258', 'Polinésia Francesa');
INSERT INTO countries VALUES ('PL', 'POL', '616', 'Polónia');
INSERT INTO countries VALUES ('PR', 'PRI', '630', 'Porto Rico');
INSERT INTO countries VALUES ('PT', 'PRT', '620', 'Portugal');
INSERT INTO countries VALUES ('QA', 'QAT', '634', 'Qatar');
INSERT INTO countries VALUES ('KE', 'KEN', '404', 'Quénia');
INSERT INTO countries VALUES ('KG', 'KGZ', '417', 'Quirguistão');
INSERT INTO countries VALUES ('GB', 'GBR', '826', 'Reino Unido da Grã-Bretanha e Irlanda do Norte');
INSERT INTO countries VALUES ('RE', 'REU', '638', 'Reunião');
INSERT INTO countries VALUES ('RO', 'ROU', '642', 'Roménia');
INSERT INTO countries VALUES ('RW', 'RWA', '646', 'Ruanda');
INSERT INTO countries VALUES ('RU', 'RUS', '643', 'Rússia');
INSERT INTO countries VALUES ('EH', 'ESH', '732', 'Saara Ocidental');
INSERT INTO countries VALUES ('AS', 'ASM', '016', 'Samoa Americana');
INSERT INTO countries VALUES ('WS', 'WSM', '882', 'Samoa (Samoa Ocidental)');
INSERT INTO countries VALUES ('PM', 'SPM', '666', 'Saint Pierre et Miquelon');
INSERT INTO countries VALUES ('SB', 'SLB', '090', 'Salomão, Ilhas');
INSERT INTO countries VALUES ('KN', 'KNA', '659', 'São Cristóvão e Névis (Saint Kitts e Nevis)');
INSERT INTO countries VALUES ('SM', 'SMR', '674', 'San Marino');
INSERT INTO countries VALUES ('ST', 'STP', '678', 'São Tomé e Príncipe');
INSERT INTO countries VALUES ('VC', 'VCT', '670', 'São Vicente e Granadinas');
INSERT INTO countries VALUES ('SH', 'SHN', '654', 'Santa Helena');
INSERT INTO countries VALUES ('LC', 'LCA', '662', 'Santa Lúcia');
INSERT INTO countries VALUES ('SN', 'SEN', '686', 'Senegal');
INSERT INTO countries VALUES ('SL', 'SLE', '694', 'Serra Leoa');
INSERT INTO countries VALUES ('RS', 'SRB', '688', 'Sérvia');
INSERT INTO countries VALUES ('SC', 'SYC', '690', 'Seychelles');
INSERT INTO countries VALUES ('SG', 'SGP', '702', 'Singapura');
INSERT INTO countries VALUES ('SY', 'SYR', '760', 'Síria');
INSERT INTO countries VALUES ('SO', 'SOM', '706', 'Somália');
INSERT INTO countries VALUES ('LK', 'LKA', '144', 'Sri Lanka');
INSERT INTO countries VALUES ('SZ', 'SWZ', '748', 'Suazilândia');
INSERT INTO countries VALUES ('SD', 'SDN', '736', 'Sudão');
INSERT INTO countries VALUES ('SE', 'SWE', '752', 'Suécia');
INSERT INTO countries VALUES ('CH', 'CHE', '756', 'Suíça');
INSERT INTO countries VALUES ('SR', 'SUR', '740', 'Suriname');
INSERT INTO countries VALUES ('SJ', 'SJM', '744', 'Svalbard e Jan Mayen');
INSERT INTO countries VALUES ('TH', 'THA', '764', 'Tailândia');
INSERT INTO countries VALUES ('TW', 'TWN', '158', 'Taiwan');
INSERT INTO countries VALUES ('TJ', 'TJK', '762', 'Tajiquistão');
INSERT INTO countries VALUES ('TZ', 'TZA', '834', 'Tanzânia');
INSERT INTO countries VALUES ('TF', 'ATF', '260', 'Terras Austrais e Antárticas Francesas (TAAF)');
INSERT INTO countries VALUES ('IO', 'IOT', '086', 'Território Britânico do Oceano Índico');
INSERT INTO countries VALUES ('TL', 'TLS', '626', 'Timor-Leste');
INSERT INTO countries VALUES ('TG', 'TGO', '768', 'Togo');
INSERT INTO countries VALUES ('TK', 'TKL', '772', 'Toquelau');
INSERT INTO countries VALUES ('TO', 'TON', '776', 'Tonga');
INSERT INTO countries VALUES ('TT', 'TTO', '780', 'Trindade e Tobago');
INSERT INTO countries VALUES ('TN', 'TUN', '788', 'Tunísia');
INSERT INTO countries VALUES ('TC', 'TCA', '796', 'Turks e Caicos');
INSERT INTO countries VALUES ('TM', 'TKM', '795', 'Turquemenistão');
INSERT INTO countries VALUES ('TR', 'TUR', '792', 'Turquia');
INSERT INTO countries VALUES ('TV', 'TUV', '798', 'Tuvalu');
INSERT INTO countries VALUES ('UA', 'UKR', '804', 'Ucrânia');
INSERT INTO countries VALUES ('UG', 'UGA', '800', 'Uganda');
INSERT INTO countries VALUES ('UY', 'URY', '858', 'Uruguai');
INSERT INTO countries VALUES ('UZ', 'UZB', '860', 'Usbequistão');
INSERT INTO countries VALUES ('VU', 'VUT', '548', 'Vanuatu');
INSERT INTO countries VALUES ('VA', 'VAT', '336', 'Vaticano');
INSERT INTO countries VALUES ('VE', 'VEN', '862', 'Venezuela');
INSERT INTO countries VALUES ('VN', 'VNM', '704', 'Vietname');
INSERT INTO countries VALUES ('VI', 'VIR', '850', 'Virgens Americanas, Ilhas');
INSERT INTO countries VALUES ('VG', 'VGB', '092', 'Virgens Britânicas, Ilhas');
INSERT INTO countries VALUES ('WF', 'WLF', '876', 'Wallis e Futuna');
INSERT INTO countries VALUES ('ZM', 'ZMB', '894', 'Zâmbia');
INSERT INTO countries VALUES ('ZW', 'ZWE', '716', 'Zimbabwe');

